apiVersion: v1
kind: Pod
metadata:
  name: nvidia-gpu-test
spec:
  restartPolicy: Never
  containers:
    - name: gpu-check
      image: nvidia/cuda:12.3.2-base-ubuntu22.04
      command: ["nvidia-smi"]
      resources:
        limits:
          nvidia.com/gpu: 1

